from custom.views.views_distrito import *
from custom.views.views_subdistrito import *
from custom.views.views_suco import *
from custom.views.views_aldeia import *
from custom.views.views_ano import *
from custom.views.views_dep import *
from custom.views.views_classe import *
from custom.views.views_periodu import *
from custom.views.views_turma import *
from custom.views.views_materia import *
from custom.views.views_ajax import *